config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get '/flights', to: 'flights#index'
  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: :Flight, foreign_key: :departure_id
  has_many :arriving_flights , class_name: :Flight, foreign_key: :arrival_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many   :passengers
  belongs_to :flight

  accepts_nested_attributes_for :passengers, reject_if: proc { |attributes|
                                                               attributes['name'].blank? ||
                                                               attributes['email'].blank? }
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: :Airport, foreign_key: :departure_id
  belongs_to :to_airport  , class_name: :Airport, foreign_key: :arrival_id
  has_many   :bookings

  def flight_date_formatted
    departure_time.strftime("%d-%m-%Y")
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings
  has_many :flights

  validates :name , presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:booking][:flight_id])
    @booking = Booking.new
    @num_passengers = params[:booking][:num_tickets].to_i
    @num_passengers.times { @booking.passengers.build }

    render :new
  end

  def create
    @booking = Booking.new(booking_params)
    @passengers = @booking.passengers

    if @booking.save
      @passengers.each do |passenger|
        PassengerMailer.with(booking: @booking, passenger: passenger).thanks_email.deliver_now
      end
     redirect_to @booking
    else
     flash.now[:danger] = "Something went wrong!"
     render :new
   end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map{ |airport| [airport.name, airport.id] }
    @departure_times = Flight.all.map{ |flight| [flight.flight_date_formatted] }.uniq

    unless params[:flight_search].nil?
      user_departure = DateTime.parse(params[:flight_search][:departure_time])
      #find all flights that match from_airport, to_airport and selected date
      @results = Flight.where(departure_id: params[:flight_search][:from_airport],
                                arrival_id: params[:flight_search][:to_airport],
                            departure_time: (user_departure.beginning_of_day..user_departure.end_of_day))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<%= render 'flights/info' %>
<br>
<%= form_for(@booking) do |f| %>
  <%= f.text_field :flight_id, value: @flight.id, type: :hidden %>
  <h3>Passenger Info:</h3>
    <%= f.fields_for(:passengers) do |p| %>
      <%= p.label :name %>
      <%= p.text_field :name %>

      <%= p.label :email %>
      <%= p.email_field :email %>
      <br>
    <% end %>
    <br>
  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<%= render 'flights/info' %>
<br>
<h3>Passenger Info:</h3>
<table>
  <thead>
    <tr>
      <td>Name:</td>
      <td>Email:</td>
    </tr>
  </thead>
<% @booking.passengers.to_a.each do |passenger| %>
  <tr>
    <td><%= passenger.name %></td>
    <td><%= passenger.email %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to "Home", root_path %>

app/views/flights/_form_flight_search.html.erb
<%= form_for('flight_search', url: root_path, method: :get) do |f| %>
  <%= f.label :from_airport %>
  <%= f.select(:from_airport, @airport_options) %>

  <%= f.label :to_airport %>
  <%= f.select(:to_airport, @airport_options) %>

  <%= f.label :num_tickets %>
  <%= f.select(:num_tickets, [1,2,3,4]) %>

  <%= f.label :departure_time %>
  <%= f.select(:departure_time, @departure_times) %>

  <%= f.submit "Search" %>

<% end %>

app/views/flights/_info.html.erb
<h3>Flight Info:</h3>
<table>
  <thead>
    <tr>
      <td>Flight id</td>
      <td>From airport</td>
      <td>To airport</td>
      <td>Flight date</td>
    </tr>
  </thead>
    <tr>
      <td><%= @flight.id %></td>
      <td><%= @flight.from_airport.code %></td>
      <td><%= @flight.to_airport.code %></td>
      <td><%= @flight.departure_time %></td>
    </tr>
</table>

app/views/flights/index.html.erb
<%= render 'form_flight_search' %>
<br>
<% unless @results.nil? || @results.empty?%>
  <table>
    <thead>
      <tr>
        <td>Selected</td>
        <td>From airport</td>
        <td>To airport</td>
        <td>Flight date</td>
      </tr>
    </thead>
  <%= form_for('booking', url: new_booking_path, method: :get) do |f| %>
    <% @results.each do |result| %>
      <tr>
        <td><%= f.radio_button(:flight_id, result.id) %></td>
        <td><%= result.from_airport.code %></td>
        <td><%= result.to_airport.code %></td>
        <td><%= result.departure_time %></td>
      </tr>
    <% end %>
    </table>
    <%= f.number_field :num_tickets, value: params[:flight_search][:num_tickets], type: :hidden %>
    <%= f.submit "Submit" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>